version: "3.7"

services:
  backend:
    image: backend-pucflix
    ports:
      - "5000:5000"
  frontend:
    build: .
    environment:
      - VITE_API_URL=http://backend:5000/
    ports:
      - "8080:80"
    depends_on:
      - backend
